language: swift
os: osx
osx_image: xcode10
xcode_project: PDF Web View.xcodeproj
xcode_scheme: PDF Web View
script: xcodebuild -scheme PDF\ Web\ View install DSTROOT=~ CODE_SIGN_IDENTITY=""
# xcode_destination: platform=iOS Simulator,OS=11.4.1,name=iPhone X
# xcodebuild -project PDF\ Web\ View.xcodeproj -scheme PDF\ Web\ View -destination platform\=iOS\ Simulator,OS\=11.4.1,name\=iPhone\ X build test 
